language: d

d:
  - dmd
  - ldc
  - gdc

script:
  - dub build
  - dub build -c panels
  - dub build -c full
  - |
    for E in examples/*/dub.json ; do
      EXAMPLE="$(dirname ${E#*/})"
      dub build "ncurses:$EXAMPLE"
    done
