language: d

os:
  - linux
  - osx

d:
  - dmd
  - ldc
  - gdc

matrix:
  exclude:
  - os: osx
    d: gdc

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ncurses; fi

script:
  - dub build
  - dub build -c panels
  - dub build -c full
  - |
    for E in examples/*/dub.json ; do
      EXAMPLE="$(dirname ${E#*/})"
      dub build "ncurses:$EXAMPLE"
    done
